# Generated by Django 2.2.2 on 2020-01-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCompress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(default=None, max_length=254, upload_to='text')),
            ],
        ),
    ]
