# Generated by Django 2.2.2 on 2020-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_textcompress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDecompress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decompress_text', models.FileField(default=None, max_length=254, upload_to='text')),
            ],
        ),
    ]
