# Generated by Django 2.2.2 on 2020-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_textdecompress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDecompress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decompress_image', models.ImageField(default=None, upload_to='photos')),
            ],
        ),
    ]
