# Generated by Django 2.2.2 on 2020-01-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagedecompress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedecompress',
            name='decompress_image',
            field=models.FileField(default=None, max_length=254, upload_to='text'),
        ),
    ]
